### ISSUE TITLE
Story generation should handle follow-up utterances, buttons, and simple yes/no modules

### ISSUE THREAD

**Issue by ortsaCniveK** [Botmock/botmock-rasa-export#10]
This is a expansion upon #7.

# Follow up Utterance
Currently, stories will be generated from a mapping of intents to messages that they're connected to.  This is good for simple flows in which each intent is mapped directly to an utterance (like an FAQ/Q&A module), however, there are times in which a chatbot might need to have a follow-up utterance after the coupled utterance is used.  Essentially all that's needed is to check and see if there's a followup message. For example:

```txt
User: What's the weather like in LA?
Bot: The weather forecast is sunny with 3% chance of rain.
Bot: Would you like a 5-day forecast as well?
```
Should be mapped as:
```md
## story:weather_report
* weather_report
 - utter_one_day_forecast
 - utter_prompt_5_day_forecast
```

# Buttons

Buttons should be handled within stories as Rasa supports them:
```yml
text: "Hey! How are you?"
    buttons:
    - title: "great" # should have quotes around title and body, with text it's optional
      payload: "great"
    - title: "super sad" # need to check to see if the payload is another intent, if so, include in Rasa format for 100% confidence intent detection, useful in some cases
      payload: "/sad"
```

# Yes/No Modules
Simple yes/no modules written with checkpoints should also be handled by the exporter:

```md
## first story
* hello
   - action_ask_user_question
> check_asked_question <!-- Checkpoint declaration -->

## user affirms question
> check_asked_question <!-- Checkpoint usage -->
* affirm
  - action_handle_affirmation

## user denies question
> check_asked_question <!-- Checkpoint usage -->
* deny
  - action_handle_denial
```
